apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task2
  template:
    metadata:
      labels:
        app: task2
    spec:
      containers:
        - name: task2
          image: sanjayrajesh/kaiburr_repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb+srv://<username>:<password>@cluster0.u6dsbqn.mongodb.net/?retryWrites=true&w=majority"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "mytasklist"
---
apiVersion: v1
kind: Service
metadata:
  name: task2-service
spec:
  selector:
    app: task2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
